---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
    {{- include "k8s-keystone-auth.labels" . | nindent 4 }}
  name: system:{{ include "k8s-keystone-auth.fullname" .  }}
  namespace: kube-system
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
      - services
      - pods
    verbs:
      - get
      - list
      - watch
